/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.manegame;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.time.Duration;
import java.time.Instant;
import org.apache.maven.shared.utils.StringUtils;

/**
 *  This class opens a new JFrame as the game interface for the user.
 * @author Sam
 */
public class LevelGUI extends javax.swing.JFrame {
   
    PlayerIcon playerIcon;
    private Timer timer;
    List<DeductionObject> deductIcons = new ArrayList<>();
    List<BenefitObject> benefitIcons = new ArrayList<>();
    public static List<BarrierObject> barrierIcons = new ArrayList<>();
    int numOfBenefitObjects = 72;
    public static int MAX_Y_AXIS = 506;
    public static int MIN_Y_AXIS = 25;
    public static int MAX_X_AXIS = 480;
    public static int MIN_X_AXIS = 50;
    int MIN_DIST_TO_ICON = 25;
    int SPACE_BETWEEN_BENEFIT_OBJECTS = 60;
    long playerScore;
    Instant start = Instant.now();
    Player player;


    /**
     * Creates new form LevelGUI
     * @param p
     */
    public LevelGUI (Player p){
        
        player = p;

        addPlayerIcon();
        addDeductIcons();
        addBenefitIcon();
        addVerticalBarrierIcons();
        
        initComponents();
        lblPlayerName.setText(p.playerName);
        lblLevel.setText(Integer.toString(p.playerLevel));
        playerScore = p.playerScore;
        lblScore.setText(Long.toString(playerScore)); 
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                close();
            }
        });

        try {
            ManeDB.dbLogBeginEvent(p.playerID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LevelGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Failed to connect to "
                    + "database your game is not being logged.");
        } catch (SQLException ex) {
            Logger.getLogger(LevelGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Connected database, but failed to log");
        }    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayerName = new javax.swing.JLabel();
        lblTitleScore = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblTitleLevel = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(570, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(570, 650));
        getContentPane().setLayout(null);

        lblPlayerName.setText("Player's Name");
        getContentPane().add(lblPlayerName);
        lblPlayerName.setBounds(0, 0, 66, 13);

        lblTitleScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitleScore.setText("Score:");
        getContentPane().add(lblTitleScore);
        lblTitleScore.setBounds(72, 0, 53, 13);

        lblScore.setText("88888888888");
        getContentPane().add(lblScore);
        lblScore.setBounds(131, 0, 53, 13);

        lblTitleLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitleLevel.setText("Level:");
        getContentPane().add(lblTitleLevel);
        lblTitleLevel.setBounds(190, 0, 53, 13);

        lblLevel.setText("XXX");
        getContentPane().add(lblLevel);
        lblLevel.setBounds(249, 0, 31, 13);

        lblTimer.setText("Timer");
        getContentPane().add(lblTimer);
        lblTimer.setBounds(443, 0, 59, 13);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        btnStart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                playerDirectionChange(evt);
            }
        });
        getContentPane().add(btnStart);
        btnStart.setBounds(240, 560, 69, 21);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        
        playerIcon.playerDirection = 0;
        timer = new Timer(10, new ActionListener(){ // every 5 milliseconds action repeats
            
            @Override
            public void actionPerformed(ActionEvent e){
                
                playerIcon.playerMove(playerIcon);
                
                for (DeductionObject d : deductIcons){ // loop to see if player hit deduct icon
                    if (playerIcon.label.getLocation().x > d.label.getLocation().x - MIN_DIST_TO_ICON &&
                            playerIcon.label.getLocation().x < (d.label.getLocation().x + MIN_DIST_TO_ICON) &&
                            playerIcon.label.getLocation().y > (d.label.getLocation().y - MIN_DIST_TO_ICON) && 
                            playerIcon.label.getLocation().y < (d.label.getLocation().y + MIN_DIST_TO_ICON) &&
                            d.label.isShowing() == true){
                        
                            d.label.setVisible(false);
                            d.hideDeductionObject(d);
                        
                            playerIcon.speed = 1;
                            playerIcon.slowPlayer(playerIcon);
                            playerScore -= d.hitDeductionObject(deductIcons.indexOf(d));
                                if (playerScore < 0) {
                                    playerScore = 0;
                                    
                                }
                    }
                    d.objectMove(d, deductIcons.indexOf(d));                     
                } 
               
                for (BenefitObject b : benefitIcons){
                    int benefitAmount = 0;
                    if ((playerIcon.label.getLocation().x > (b.label.getLocation().x - MIN_DIST_TO_ICON) && 
                            playerIcon.label.getLocation().x < (b.label.getLocation().x + MIN_DIST_TO_ICON)) &&
                            (playerIcon.label.getLocation().y > (b.label.getLocation().y - MIN_DIST_TO_ICON) && 
                            playerIcon.label.getLocation().y < (b.label.getLocation().y + MIN_DIST_TO_ICON)) &&
                            b.label.isShowing() == true){
                        benefitAmount = b.hitBenefitObject(benefitIcons.indexOf(b));
                        playerScore += benefitAmount;
                        b.label.setVisible(false);
                        --numOfBenefitObjects;
                    }
                    lblScore.setText(Long.toString(playerScore));
                    if (numOfBenefitObjects == 0) {
                       timer.stop();
                       endOfLevel();
                       break;
                       
                    }
                }
            }                           
        });
        timer.start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void playerDirectionChange(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerDirectionChange
        if( (evt.getKeyCode() == KeyEvent.VK_DOWN) && (playerIcon.label.getLocation().y <= MAX_Y_AXIS) ){
            if (playerIcon.hitBottomBarrier(playerIcon) == false) {
                playerIcon.playerDirection = 2;
            }
        }   
        if( (evt.getKeyCode() == KeyEvent.VK_UP) && (playerIcon.label.getLocation().y >= MIN_Y_AXIS) ){
            if (playerIcon.hitTopBarrier(playerIcon) == false){
                   playerIcon.playerDirection = 0;
            }
        }
        if( (evt.getKeyCode() == KeyEvent.VK_LEFT) && (playerIcon.label.getLocation().x >= MIN_X_AXIS) ){
            if (playerIcon.hitLeftBarrier(playerIcon) == false){
                  playerIcon.playerDirection = 1;
            }
        }
        if( (evt.getKeyCode() == KeyEvent.VK_RIGHT) && (playerIcon.label.getLocation().x <= MAX_X_AXIS) ){
            if (playerIcon.hitRightBarrier(playerIcon) == false){
                  playerIcon.playerDirection = 3;
            }
        }
    }//GEN-LAST:event_playerDirectionChange

    /**
     * @param p the command line arguments
     */
    public static void main (Player p) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelGUI(p).setVisible(true);
            }
        });
    }
    
    public final void addDeductIcons(){
       
        for (int i = 0; i < 3; i++) {
        DeductionObject d = new DeductionObject();        
        deductIcons.add(d);
        d.setIconImage(d, i);
        add(d.label, BorderLayout.CENTER);
        d.label.setVisible(true);     
        }
    }
       
    /**
     * Adds the player icon to the board.
     */
    public final void addPlayerIcon(){
         
        playerIcon = new PlayerIcon();
        playerIcon.setPlayerImage(playerIcon);
        add(playerIcon.label, BorderLayout.CENTER);
        playerIcon.label.setLocation(MIN_X_AXIS, MIN_Y_AXIS);
        playerIcon.label.setVisible(true);  
    }
    
    /**
     * Adds vertical barriers to the board spaced between benefit objects.
     * 
     */
    public final void addVerticalBarrierIcons(){
        int barrierWidth = 15;
        int barrierHeight = 100;
        int j = 0;
        
        for ( int barrierXaxis = SPACE_BETWEEN_BENEFIT_OBJECTS; barrierXaxis < MAX_X_AXIS; barrierXaxis += SPACE_BETWEEN_BENEFIT_OBJECTS ) {
           
            if (barrierXaxis % (SPACE_BETWEEN_BENEFIT_OBJECTS*2) == 0){
                barrierIcons.add(new BarrierObject());
                barrierIcons.get(j).verticalBarrier();
                add(barrierIcons.get(j).label, BorderLayout.CENTER);
                barrierIcons.get(j).label.setLocation(barrierXaxis + 27, MIN_Y_AXIS);
                barrierIcons.get(j).label.setVisible(true);
                j++;
                
                barrierIcons.add(new BarrierObject());
                barrierIcons.get(j).verticalBarrier();
                add(barrierIcons.get(j).label, BorderLayout.CENTER);
                barrierIcons.get(j).label.setLocation(barrierXaxis + 27, MAX_Y_AXIS - barrierHeight);
                barrierIcons.get(j).label.setVisible(true);
                j++;
            }
            else {

                barrierIcons.add(new BarrierObject());
                barrierIcons.get(j).verticalBarrier();
                add(barrierIcons.get(j).label, BorderLayout.CENTER);
                barrierIcons.get(j).label.setLocation(barrierXaxis + 27, (MAX_Y_AXIS/2) - (barrierHeight/2) + MIN_Y_AXIS);
                barrierIcons.get(j).label.setVisible(true);      
                j++;
            }
            
        }
        
    }
    
    
    /**
     * Close events save player's info to All Player's table and to their log table.
     * 
     */
    private void close() {
            
        Instant finish = Instant.now();
        Duration gameTime = Duration.between(start, finish);
        long gameInSeconds = gameTime.getSeconds();
        long gameInMinutes = gameInSeconds /  60;
        long gameInHours = gameInMinutes / 60;
            // HH:MM:SS
        String gameTimeString = Long.toString(gameInHours) + ":" 
            + StringUtils.leftPad(Long.toString(gameInMinutes), 2, "0") + ":" 
            + StringUtils.leftPad(Long.toString(gameInSeconds % 60), 2, "0");
        try {
            ManeDB.dbLogEndEvent(player, gameTimeString);
            ManeDB.dbSaveCurrentStatus(player, player.playerLevel, playerScore);
            
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LevelGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Failed to log");
        } catch (SQLException ex) {
            Logger.getLogger(LevelGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Add benefit icons to the board.
     */
    public final void addBenefitIcon(){
        int benefitObjectXaxis = MIN_X_AXIS;
        int benefitObjectYaxis = MIN_Y_AXIS;
        
        // Loop through the number of benefit objects
        // add JLabel for each object.
        for (int i = 0; i < numOfBenefitObjects; i++) {
            if (benefitObjectYaxis < MAX_Y_AXIS) {
                BenefitObject b = new BenefitObject();        
                if (i % 3 == 0){
                    benefitIcons.add(b);
                    b.benefitIconImage(b, 1);
                    }
                else if (i % 2 == 0){
                    benefitIcons.add(b);
                    b.benefitIconImage(b, 2);
                }
                else {
                    benefitIcons.add(b);
                    b.benefitIconImage(b, 0);
                }
                // add the new JLabel to the board.
                add(b.label, BorderLayout.CENTER);
                // set the benefit object location.
                b.label.setLocation(benefitObjectXaxis, benefitObjectYaxis);
                b.label.setVisible(true);  
                benefitObjectYaxis += SPACE_BETWEEN_BENEFIT_OBJECTS;
            }
            // start a new column of benefit objects.
            if (benefitObjectYaxis >= MAX_Y_AXIS){
                benefitObjectXaxis += SPACE_BETWEEN_BENEFIT_OBJECTS;
                benefitObjectYaxis = MIN_Y_AXIS;
            }
        }  
    }
    
    private void endOfLevel(){
        
        player.playerLevel += 1;
        close();
        LevelGUI nextLevel;
        try {
            nextLevel = new LevelGUI(ManeDB.dbGetPlayerData(player.playerEmail));
            nextLevel.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LevelGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LevelGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
    }
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTitleLevel;
    private javax.swing.JLabel lblTitleScore;
    // End of variables declaration//GEN-END:variables

}
