package com.manegame;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import org.apache.maven.shared.utils.StringUtils;
import org.junit.Assert;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *  This class executes the initial user interface.  User's can choose to 
 *  login or to register as a new player.
 * @author Sam
 */
public class NewUserForm extends javax.swing.JFrame {

    String name;
    String email;
    String password;
    
    /**
     * Creates new form NewUserForm
     */
    public NewUserForm() {
        initComponents();
        txtPassword.setEchoChar('*');
        txtVerifyPassword.setEchoChar('*');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblReturnUser = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblVerifyPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtVerifyPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(475, 400));
        getContentPane().setLayout(null);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");
        getContentPane().add(lblName);
        lblName.setBounds(52, 76, 67, 17);

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(52, 109, 67, 17);

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtName);
        txtName.setBounds(132, 73, 290, 23);

        btnRegister.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.setActionCommand("btnRegister");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(167, 233, 114, 23);

        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setActionCommand("btnLogin");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(167, 289, 114, 23);

        lblReturnUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblReturnUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReturnUser.setText("Returning User?");
        getContentPane().add(lblReturnUser);
        lblReturnUser.setBounds(167, 262, 114, 17);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Welcome to the Mane Game");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(96, 27, 263, 22);

        lblPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Password:");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(50, 140, 70, 17);

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(132, 106, 290, 23);

        lblVerifyPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblVerifyPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVerifyPassword.setText("Verify Password:");
        getContentPane().add(lblVerifyPassword);
        lblVerifyPassword.setBounds(10, 180, 112, 17);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(130, 140, 290, 23);
        getContentPane().add(txtVerifyPassword);
        txtVerifyPassword.setBounds(130, 180, 290, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
                   
        try {
            name = txtName.getText();
            email = txtEmail.getText();
            
            if (ManeDB.dbVerifyLoginEmail(email) == false)    {
                // Verify password fields match
                if (txtPassword.getText().equals(txtVerifyPassword.getText())) {
                    password = txtPassword.getText();
                    
                    //check that all input is valid
                    if (validInputName(name) == true && validInputEmail(email) == true && validInputPassword(password) == true) {
                        Player p = new Player(name, email, password);
                        
                        try {
                            ManeDB.dbSaveNewPlayer(p);
                            ManeDB.dbCreatePlayerLogTable(p.playerID);
                            new LevelGUI(p).setVisible(true);
                        }
                        catch (ClassNotFoundException ex) {
                            Logger.getLogger(NewUserForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        catch (SQLException ex) {
                            Logger.getLogger(NewUserForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                else { 
                    JOptionPane.showMessageDialog(null,"Passwords must match");
                    txtPassword.hasFocus();
                    txtVerifyPassword.setText("");
                }
            }
            else {
                JOptionPane.showMessageDialog(null,"You already have an account");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewUserForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewUserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed
    
    /**
     * Verify valid user input name for the New User Form.  
     * @param String name
     * @return
     */
    public boolean validInputName(String name){
        boolean inputValid = false;
        
        if (Pattern.matches("[a-zA-Z0-9\\s\\-]{1,50}", name)){
            inputValid = true;
            StringUtils.countMatches(name.replace(" ", ""), "--"); //replace spaces --
        }
        else {
            JOptionPane.showMessageDialog(null,"Name can only contain letters, digits, "
                    + "and hyphens");
            txtName.setText("");
            txtName.hasFocus();
        }

        return inputValid;
    }
    
     /**
     * Verify valid user input email for the New User Form.  
     * @param String email
     * @return 
     */
    public boolean validInputEmail (String inputEmail) {
	boolean inputValid = false;
        String validEmail = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        if (email.matches(validEmail)){
            inputValid = true;
        }    
        else {
            JOptionPane.showMessageDialog(null,"Please Enter a Valid Email Address");
            txtEmail.setText("");
            txtEmail.hasFocus();
        }
        return inputValid;
    }
    
     /**
     * Verify valid user input password for the New User Form.  
     * @param String password
     * @return 
     */
    public boolean validInputPassword (String inputPassword){
	boolean validPassword = false;
        String passwordChecker = "((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,20})";
        if (password.matches(passwordChecker)) {
            validPassword = true;
        }
        else {
            JOptionPane.showMessageDialog(null,"Password must be 6 - 20 characters\n" +
                    "Must have at least one lower case letter\nAt least one upper case letter\n" +
                    "And one of the following special characters @, #, $, %");
            txtPassword.setText("");
            txtVerifyPassword.setText("");
            txtPassword.hasFocus();
        }
	return validPassword;
    }
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private static class LoginWindow implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e){ 
            //opens the maintenance window
            new LoginForm().setVisible(true);            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblReturnUser;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVerifyPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtVerifyPassword;
    // End of variables declaration//GEN-END:variables
}
